name = "webhookcatch"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "webhookcatch"
database_id = "6206b37d-aa88-493f-a521-c3704760f693"

[triggers]
crons = [ "* * * * *" ] # Run every minute

[[kv_namespaces]]
binding = "SESSION"
id = "f805ba1691a3417ab6c2e2b2023f176a"



[vars]
TURNSTILE_SECRET_KEY = ""
TURNSTILE_SITE_KEY = ""
