name = "webhookcatch"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB"
database_name = "webhookcatch-db"
database_id = "00000000-0000-0000-0000-000000000000"

[triggers]
crons = [ "* * * * *" ] # Run every minute
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SESSION"
id = "0469c1c2b4d644dfa15974646a905d0e"
migrations_dir = "migrations"



[vars]
TURNSTILE_SECRET_KEY = ""
TURNSTILE_SITE_KEY = ""
